select *from USERS

select * from ADRESS where USERID=1

SELECT USERS.* FROM
USERS, ADRESS

WHERE USERS.ID = ADRESS.USERID
AND USERS.ID =4

-----------------------------------------------------


SELECT 
U.NAMESURNAME,U.EMAIL,U.GENDER,
U.BIRTHDATE,
C.COUNTRY,
A.ADRESSTEXT,
CT.CITY,
T.TOWN AS D,D.DISTRICT,
A.*

FROM
USERS U,ADRESS A, COUNTRÝES C, CTIES CT,
TOWNS T,  DISTRICTS D

WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID AND CT.ID= A.CITYID
AND U.ID =4 AND T.ID = A.TOWNID AND D.ID = A.DISRICTID 

ORDER BY U.USERNAME_
-----------------------------------------------
SELECT 
U.NAMESURNAME,U.EMAIL,U.GENDER,
U.BIRTHDATE,
A.ADRESSTEXT,

A.*

FROM
USERS U,ADRESS A

WHERE U.ID = A.USERID
AND U.ID =4  

ORDER BY U.USERNAME_
