--ASCII VE CHAR FONK
SELECT ASCII('3')
SELECT CHAR(65) -- HARF KARÞILIÐINDA NE GELÝYOR BUNU HESAPLA
SELECT CHAR(ASCII('Ö'))

-- SUBSTRING---
--BÝR STÝRÝNG ÝÇÝERSÝNDE BÝR NOKTADAN BAÞKA NOKTAYA PARÇALAMAK ÝÇÝ KULLANILIR.,
SELECT SUBSTRING('BARBOROS HALÝT TAÞDEMÝR' ,6,6)