SELECT MIN(AMOUNT), MAX(AMOUNT) FROM SALES -- MÝN ÝLE MAX SALES MÝKTARLARINI ÖÐRNEMEK ÝSTEDÝÐÝMÝZDE KULLANIRIZ.

SELECT SUM(AMOUNT) FROM SALES

SELECT AVG(AMOUNT) FROM SALES

SELECT * FROM SALES
ORDER BY TOTALPRICE

SELECT AVG(TOTALPRICE), MIN(TOTALPRICE), MAX(TOTALPRICE), SUM(TOTALPRICE) FROM SALES
WHERE CITY ='ANKARA'
