SELECT  TOP 10
CITY,SUM(TOTALPRICE) 
FROM SALES

 GROUP BY CITY  
 ORDER BY SUM(TOTALPRICE) DESC

 --BÝR MAÐZANIN GÜN BAZLI SATIÞ RAKAMLARINI GETÝRME

  SELECT *,
  CONVERT(DATE,DATE_) AS DATE2
  FROM SALES WHERE CITY = 'ANKARA'
  ORDER BY DATE_

  SELECT CONVERT(DATE,'2019-01-01 08:07:24.000') -- ÝKÝ FARKLI DATE TÜRÜ OLDUÐUNU BELLÝ EDÝYOR.
  SELECT CONVERT(datetime,'2019-01-01 08:07:24.000')

  UPDATE SALES SET DATE2 = CONVERT(DATE,DATE_) 
  -- YANÝ BURDA ÝKÝ FARKLI DATE OLDUÐUNDAN BAHSEDÝLÝYOR BÝRÝ NORMAL AY YIL GÜN OLAN DÝÐERÝ AY GÜN YIL SAAT DAKKA SANÝYE
 
  SELECT *
  FROM SALES WHERE CITY ='ANKARA'
  --AND DATE2 = '2019-01-01'
  AND DATE_ = '2019-01-01 00:00:00'
  ORDER BY DATE_

  SELECT *
  FROM SALES WHERE CITY ='ANKARA'
  ORDER BY DATE_


  SELECT CITY, DATE2, SUM(TOTALPRICE) AS TOTALPRICE
  FROM SALES WHERE CITY = 'ANKARA'
  GROUP BY CITY, DATE2
  ORDER BY CITY, DATE2

  --------------------------------------------------------------------

  SELECT  DATE2, CITY,SUM(TOTALPRICE) FROM SALES
  WHERE DATE2 = '2019-01-01'
  GROUP BY DATE2 , CITY
  ORDER BY DATE2,CITY
  ---- SORGU	 ***** TAÝHÝNDEN SONRA ÞEHÝR ANKARA OLAN ÜRÜNLERÝN TOPLAM SATIÞ TUTATLARINI EKRANA GETÝR.
  
  SELECT DATE2,CITY, SUM(TOTALPRICE) FROM SALES
  WHERE DATE2 >= '2019-01-01' AND CITY = 'ANKARA'
  GROUP BY DATE2,CITY
  ORDER BY DATE2,CITY

  SELECT  DATE2, CITY,SUM(TOTALPRICE) FROM SALES
  WHERE DATE2 = '2019-01-01'
  GROUP BY DATE2 , CITY
  ORDER BY DATE2, SUM(TOTALPRICE) DESC


  SELECT * FROM SALES
  WHERE DATE2 ='2019-01-01'
 
 ------ MAÐZALARIN AYLARA GÖRE SATIÞ RAKAMLARINI GETÝRME------

--   excel kullanarak veri çekmek istediðinde "localhost" kullan.

