SELECT* FROM SALES

SELECT DATEPART(MONTH,'2019-08-02')

UPDATE SALES SET MONTHNAME = '01.OCAK' WHERE DATEPART(MONTH,DATE2) = 1
UPDATE SALES SET MONTHNAME = '02.ÞUBAT' WHERE DATEPART(MONTH,DATE2) = 2
UPDATE SALES SET MONTHNAME = '03.MART' WHERE DATEPART(MONTH,DATE2) = 3
UPDATE SALES SET MONTHNAME = '04.NÝSAN' WHERE DATEPART(MONTH,DATE2) = 4
UPDATE SALES SET MONTHNAME = '05.MAYIS' WHERE DATEPART(MONTH,DATE2) = 5
UPDATE SALES SET MONTHNAME = '06.HAZÝRAN' WHERE DATEPART(MONTH,DATE2) = 6
UPDATE SALES SET MONTHNAME = '07.TEMMUZ' WHERE DATEPART(MONTH,DATE2) = 7
UPDATE SALES SET MONTHNAME = '08.AÐUSTOS' WHERE DATEPART(MONTH,DATE2) = 8
UPDATE SALES SET MONTHNAME = '09.EYLÜL' WHERE DATEPART(MONTH,DATE2) = 9
UPDATE SALES SET MONTHNAME = '10.EKÝM' WHERE DATEPART(MONTH,DATE2) = 10
UPDATE SALES SET MONTHNAME = '11.KASIM' WHERE DATEPART(MONTH,DATE2) = 11
UPDATE SALES SET MONTHNAME = '12.ARALIK' WHERE DATEPART(MONTH,DATE2) = 12
