SELECT MONTHNAME,CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES

GROUP BY CITY, MONTHNAME
ORDER BY MONTHNAME, SUM(TOTALPRICE) DESC

SELECT* FROM SALES

SELECT MONTHNAME, CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES

GROUP BY CITY, MONTHNAME
ORDER BY MONTHNAME, CITY DESC