/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[CUSTOMERNAME]
      ,[CITY]
      ,[BIRTHDATE]
      ,[DISRICT]
      ,[GENDER]
  FROM [ETRADE].[dbo].[CUSTOMERS]

  INSERT INTO CUSTOMERS
  (ID,CUSTOMERNAME,CITY,BIRTHDATE,DISRICT,GENDER)
  VALUES
  ('6','BARBOROS TAÞDEMÝR','ERZURUM','2021-09-21','NEW YOURK','E')


SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS
SET NATÝON ='TR' , AGE = 40

--------------------------------------
UPDATE CUSTOMERS
SET NATÝON ='TR', AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE()) 